name: "CI"

on:
  push:
  pull_request:

jobs:
  build-book:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Install mdbook
        run: |
          mkdir bin
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz
          tar xf mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz --directory=bin
          echo "${{github.workspace}}/bin" >> ${GITHUB_PATH}
          # not yet in PATH due to missing source command
          bin/mdbook --version

      - name: Build book
        run: |
          make all

      - name: publish book
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: success() && github.ref == 'refs/heads/main' # only deploy main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: books
